1.20 port
bl4ckscor3/CeilingTorch pull request #66
Opened 2023-06-08 16:26 UTC by gohkenytp

Ported this mod to Minecraft 1.20

2023-06-08 17:02 UTC, bl4ckscor3 requested changes
Thank you! This still needs changes which I have outlined below and in review comments.

- Upgrade the Gradle wrapper and relevant scripts to 8.1.1. Best to just copy the files from the Forge MDK.
- Please apply this change https://github.com/Geforce132/SecurityCraft/commit/f4d2a30c73c2a64c139d329c3a6f95dfb0d1f990#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7L26-R29
- Same with this one https://github.com/Geforce132/SecurityCraft/commit/f4d2a30c73c2a64c139d329c3a6f95dfb0d1f990#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7R53
- Please add this https://github.com/Geforce132/SecurityCraft/commit/f4d2a30c73c2a64c139d329c3a6f95dfb0d1f990#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7R139-R141
- The pack.mcmeta needs to be updated. It should be as seen below.
```json
{
  "pack": {
    "description": {
      "text": "Mod resources & data"
    },
    "pack_format": 15,
    "forge:server_data_pack_format": 15
  }
}
```

2023-06-08 17:02 UTC, bl4ckscor3 commented on build.gradle
> +version = '1.26'
No version increase for a Minecraft update.

2023-06-08 17:02 UTC, bl4ckscor3 commented on build.gradle
> +    mappings channel: 'official', version: '1.20'
Please use parchment. I am aware it is not updated to 1.20 yet, but I prefer incomplete parameter mappings over none.

2023-06-08 17:02 UTC, bl4ckscor3 commented on src/main/resources/META-INF/mods.toml
>  license="MIT https://github.com/bl4ckscor3/CeilingTorch/blob/1.19/LICENSE"
Update the branch to `1.20`, please.

2023-06-08 17:45 UTC, gohkenytp reviewed
I already ported this to 1.20

2023-06-08 17:46 UTC, gohkenytp reviewed
Look, not to be rude, but I ported your Ceiling Torch mod to 1.20 fair and square. Glad you like the idea.

2023-06-08 19:17 UTC, bl4ckscor3 commented
I don't understand your most recent comment. I appreciate you porting the mod, and in the usual way how pull requests go, I asked for changes to be made before the PR gets merged. There's no ill intent from my side.

I will be reviewing this again tomorrow as it's getting late here.

2023-06-08 19:39 UTC, gohkenytp commented
OK. I sure hope this goes successful!

2023-06-09 08:46 UTC, bl4ckscor3 commented on build.gradle
> +version = '1.26'
This still needs to be addressed.

2023-06-09 08:46 UTC, bl4ckscor3 commented on build.gradle
> +    mappings channel: 'official', version: '1.20'
This still needs to be addressed.

2023-06-09 08:46 UTC, bl4ckscor3 commented on src/main/resources/META-INF/mods.toml
>  license="MIT https://github.com/bl4ckscor3/CeilingTorch/blob/1.19/LICENSE"
This still needs to be addressed.

2023-06-09 08:47 UTC, bl4ckscor3 commented
From my previous review comment, 4 points have not been addressed, as well as the comments I left on the code itself.

- Upgrade the Gradle wrapper and relevant scripts to 8.1.1. Best to just copy the files from the Forge MDK.
- Please apply this change https://github.com/Geforce132/SecurityCraft/commit/f4d2a30c73c2a64c139d329c3a6f95dfb0d1f990#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7L26-R29
- Same with this one https://github.com/Geforce132/SecurityCraft/commit/f4d2a30c73c2a64c139d329c3a6f95dfb0d1f990#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7R53
- Please add this https://github.com/Geforce132/SecurityCraft/commit/f4d2a30c73c2a64c139d329c3a6f95dfb0d1f990#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7R139-R141

2023-06-09 12:38 UTC, gohkenytp commented
Ok I did it already.

2023-06-09 13:05 UTC, bl4ckscor3 commented
Not everything is addressed yet.

2023-06-09 14:18 UTC, gohkenytp commented
Look, I tried to port it, but you didn't seem to understand.

2023-06-09 14:57 UTC, bl4ckscor3 commented
I do understand. And I can just reiterate that I am happy you did the port. But it is lacking some necessary changes for it to be considered complete. I requested those changes to be made, that's how pull requests work. If you don't want to finish the port it's fine, I'll base mine off of yours once I get around to doing it. But unless you can address my previous comments, this is not getting merged.

2023-06-09 16:03 UTC, gohkenytp commented
I don't want to finish this port sadly.

2023-06-09 18:39 UTC, gohkenytp commented
Also, why are you halting progress on your port to 1.20 anyway?

2023-06-09 19:23 UTC, bl4ckscor3 commented
Please see my comment on the other repository. There's no reason to crosspost.

2023-06-09 20:22 UTC, gohkenytp commented
Not to be rude but, I just can't do it now. OK? Accept it. Maybe you can port it without me if you get a chance.

2023-06-09 20:22 UTC, closed without merging